# Generated by Django 4.1.2 on 2022-10-20 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=24)),
                ('modele', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=12)),
                ('chipset', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Processeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=5)),
                ('categorie', models.CharField(max_length=2)),
                ('modele', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=24)),
                ('frequence', models.CharField(max_length=5)),
                ('taille', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stockage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=3)),
                ('taille', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimentation', models.IntegerField()),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcMaker.gpu')),
                ('motherBoard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcMaker.motherboard')),
                ('processeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcMaker.processeur')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcMaker.ram')),
                ('stockage', models.ManyToManyField(to='pcMaker.stockage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
